app/models/LoginForm.php
<?php

/**
 * LoginForm class.
 * LoginForm is the data structure for keeping
 * user login form data. It is used by the 'login' action of 'SiteController'.
 */
class LoginForm extends CFormModel
{
    const SESSION_DURATION = 2592000; // 30 days

    public $email;
    public $password;
    public $rememberMe;

    private $_identity;



    /**
     * Declares the validation rules.
     * The rules state that username and password are required,
     * and password needs to be authenticated.
     */
    public function rules()
    {
        return array(
            array('email, password', 'required'),
            array('password', 'authenticate'),
        );
    }


    /**
     * Authenticates the password.
     * This is the 'authenticate' validator as declared in rules().
     */
    public function authenticate($attribute, $params)
    {
        if (!$this->hasErrors()) {
            $this->_identity = new UserIdentity($this->email, $this->password);
            if (!$this->_identity->authenticate()) {
                $this->addError('password', 'Incorrect username or password.');
            }
        }
    }

    /**
     * Logs in the user using the given username and password in the model.
     *
     * @return boolean whether login is successful
     */
    public function login()
    {
        if ($this->_identity === null) {
            $this->_identity = new UserIdentity($this->email, $this->password);
            $this->_identity->authenticate();
        }
        if ($this->_identity->errorCode === UserIdentity::ERROR_NONE) {
            $duration = $this->rememberMe ? self::SESSION_DURATION : 0;
            Yii::app()->user->login($this->_identity, $duration);
            $user = User::model()->findByAttributes(array('email' => $this->email));
            $user->regenerateSession();
            return true;
        } else {
            return false;
        }
    }
}

app/models/User.php
<?php


class User extends CActiveRecord
{
    const STATUS_PENDING = 0;
    const STATUS_CONFIRMED = 1;


    public function tableName()
    {
        return 'user';
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function rules()
    {
        return array(
            array('email', 'required'),
            array('email', 'email'),
            array('email', 'unique'),
            array('password, activation_code, status', 'safe')
        );
    }

    public function sendActivationLink()
    {
        $mail = Yii::app()->email;
        $mail->from = "kr.vital@gmail.com";
        $mail->to = $this->email;
        $mail->subject = 'Activation link';
        $mail->message = 'Welcome! \n Here is activation link <a href="' .
            Yii::app()->createAbsoluteUrl(
                "/site/emailConfirmation",
                array("user_id" => $this->id, "code" => $this->activation_code)
            ) . '">click here</a>';
        return $mail->send();
    }

    public function sendPassword()
    {
        $mail = Yii::app()->email;
        $mail->to = $this->email;
        $mail->subject = 'Password';
        $mail->message = 'Here is your password:  ' . $this->password;
        return $mail->send();
    }

    public function isActive()
    {
        return (bool)$this->status;
    }

    public function codeValidity($code)
    {
        return $this->activation_code == $code;
    }

    protected function beforeSave()
    {
        if ($this->isNewRecord) {
            $this->setupActivationCode();
            $this->setupPassword();
            $this->status = self::STATUS_PENDING;
        }
        return parent::beforeSave();
    }

    private function setupActivationCode()
    {
        $this->activation_code = md5(time() . $this->email);
    }

    private function setupPassword()
    {
        $this->password = $this->generatePassword();
    }

    private function generatePassword()
    {
        $alpha = "abcdefghijklmnopqrstuvwxyz";
        $numeric = "0123456789";
        $pass_length = 8;
        return substr(str_shuffle($alpha . $numeric), 0, $pass_length);
    }

    public function regenerateSession()
    {
        if(!empty($this->session_id)) {
            Yii::app()->session->destroySession($this->session_id);
        }

        $this->session_id = Yii::app()->session->sessionID;
        $this->save();
    }

}

app/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class'     => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page'    => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('index');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest) {
                echo $error['message'];
            } else {
                $this->render('error', $error);
            }
        }
    }

    /**
     * Displays the login page
     */
    public function actionLogin()
    {
        $model = new LoginForm;

        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            if ($model->validate() && $model->login()) {
                $this->redirect(Yii::app()->user->returnUrl);

            }
        }

        $this->render('login', array('model' => $model));
    }

    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }

    public function actionRegister()
    {
        $model = new User();
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'registration-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        if (isset($_POST['User'])) {
            $model->attributes = $_POST['User'];
            if ($model->save()) {
                $model->sendActivationLink();
                Yii::app()->user->setFlash('success', '<strong>Thank you for registration!</strong> Check your email.');
            }
        }
        $this->render('register', array('model' => $model));
    }

    public function actionEmailConfirmation($user_id, $code)
    {
        $user = User::model()->findByPk($user_id);
        if (!$user->isActive() && $user->codeValidity($code)) {
            $user->sendPassword();
            Yii::app()->user->setFlash('success', 'Your status is confirmed. Check your email to get password and try to login');
        }
        $this->redirect('/site/login');
    }

}

app/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

app/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

app/views/layouts/main.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<div class="container-narrow">
    <div class="masthead">
        <?php $this->widget(
            'bootstrap.widgets.TbMenu',
            array(
                 'htmlOptions' => array(
                     'class' => 'nav nav-pills pull-right'
                 ),
                 'items'       => array(
                     array('label' => 'Home', 'url' => array('/site/index')),
                     array('label' => 'Login', 'url' => array('/site/login'), 'visible' => Yii::app()->user->isGuest),
                     array(
                         'label'   => 'Logout (' . Yii::app()->user->name . ')',
                         'url'     => array('/site/logout'),
                         'visible' => !Yii::app()->user->isGuest
                     ),
                     array('label'   => 'Register',
                           'url'     => array('/site/register'),
                           'visible' => Yii::app()->user->isGuest
                     ),
                 ),
            )
        ); ?>
        <h3 class="muted"><?php echo CHtml::encode(Yii::app()->name); ?></h3>
    </div>
    <hr>
    <?php echo $content; ?>
    <hr>
    <div class="footer">
        <p>&copy; Company 2013</p>
    </div>

</div>
<!-- /container -->

</body>
</html>

app/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<h2>Error <?php echo $code; ?></h2>

<div class="error">
<?php echo CHtml::encode($message); ?>
</div>

app/views/site/index.php
<?php
/* @var $this SiteController */
CVarDumper::dump(Yii::app()->session->sessionID,10,true);
$this->pageTitle=Yii::app()->name;
?>

<h1>Welcome to <i><?php echo CHtml::encode(Yii::app()->name); ?></i></h1>

<p>Congratulations! You have successfully created your Yii application.</p>

<p>You may change the content of this page by modifying the following two files:</p>
<ul>
	<li>View file: <code><?php echo __FILE__; ?></code></li>
	<li>Layout file: <code><?php echo $this->getLayoutFile('main'); ?></code></li>
</ul>

<p>For more details on how to further develop this application, please read
the <a href="http://www.yiiframework.com/doc/">documentation</a>.
Feel free to ask in the <a href="http://www.yiiframework.com/forum/">forum</a>,
should you have any questions.</p>

app/views/site/login.php
<div class="form well span4 offset1">
    <?php
    $form = $this->beginWidget(
        'bootstrap.widgets.TbActiveForm',
        array(
             'type' => 'inline',
             'enableAjaxValidation' => true,
        )
    );
    ?>

    <fieldset>
        <?php $this->widget(
            'bootstrap.widgets.TbAlert',
            array(
                 'block'     => true,
                 'fade'      => true,
                 'closeText' => '&times;',
                 'alerts'    => array(
                     'success' => array(
                         'block'     => true,
                         'fade'      => true,
                         'closeText' => '&times;'
                     ),
                 ),
            )
        ); ?>
        <legend>Login</legend>
        <?php echo $form->errorSummary($model); ?>
        <?php echo $form->textFieldRow($model, 'email', array('placeholder' => 'Username', 'class' => 'span4', 'autofocus' => 'true'));?>
        <p></p>
        <?php echo $form->passwordFieldRow($model, 'password', array('class' => 'span4'));?>
        <p></p>
        <?php $this->widget(
            'bootstrap.widgets.TbButton',
            array(
                 'buttonType' => 'submit',
                 'label'       => 'Sign In',
                 'type'        => 'primary',
                 'block'       => true,
            )
        ); ?>
        <br>
        <p style="text-align: center"><a href="<?php echo Yii::app()->createUrl('/site/register')?>">Don't have account? Register now</a></p>
    </fieldset>
    <p></p>
    <hr>

    <?php $this->endWidget(); ?>
</div><!-- form -->

app/views/site/register.php
<div class="form well span4 offset1">
    <?php
    $form = $this->beginWidget(
        'bootstrap.widgets.TbActiveForm',
        array(
             'id'                   => 'registration-form',
             'type'                 => 'inline',
             'enableAjaxValidation' => true,
             'clientOptions'        => array(
                 'validateOnChange' => true,
                 'validateOnSubmit' => true
             )
        )
    );
    ?>
    <fieldset>
        <?php $this->widget(
            'bootstrap.widgets.TbAlert',
            array(
                 'block'     => true,
                 'fade'      => true,
                 'closeText' => '&times;',
                 'alerts'    => array(
                     'success' => array(
                         'block'     => true,
                         'fade'      => true,
                         'closeText' => '&times;'
                     ),
                 ),
            )
        ); ?>
        <legend>Registration</legend>
        <?php echo $form->errorSummary($model); ?>
        <?php echo $form->textFieldRow(
            $model,
            'email',
            array('placeholder' => 'Enter your email', 'class' => 'span4', 'autofocus' => 'true')
        );?>
        <p></p>

        <p></p>
        <?php $this->widget(
            'bootstrap.widgets.TbButton',
            array(
                 'buttonType' => 'submit',
                 'label'      => 'Register',
                 'type'       => 'primary',
                 'block'      => true,
            )
        ); ?>
    </fieldset>
    <p></p>
    <hr>
    <?php $this->endWidget(); ?>
</div><!-- form -->